/* Gemeinfrei. Public Domain. */
#if !defined(internal_System)
#include "internal.System.h"
#endif
#if !defined(have_System_ELFAssembly)
#include <min/System.ELFAssembly.h>
#endif
#if !defined(code_System_ELF32Assembly)
#define code_System_ELF32Assembly

struct System_Type  System_ELF32AssemblyType = { .base = { .type = typeof(System_Type), }, .name = "System.ELF32Assembly", };

#endif
#if !defined(code_System_ELF64Assembly)
#define code_System_ELF64Assembly

struct System_Type  System_ELF64AssemblyType = { .base = { .type = typeof(System_Type), }, .name = "System.ELF64Assembly", };

#endif
#if !defined(code_System_ELFAssembly)
#define code_System_ELFAssembly

struct System_Type_FieldInfo  System_ELFAssembly_ABITypeFields[] = {
    [0] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.None", .value = System_ELFAssembly_ABI_None },
    [1] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.SysV", .value = System_ELFAssembly_ABI_SysV },
    [2] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.HPUX", .value = System_ELFAssembly_ABI_HPUX },
    [3] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.NetBSD", .value = System_ELFAssembly_ABI_NetBSD },
    [4] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.GNU", .value = System_ELFAssembly_ABI_GNU },
    [5] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.Linux", .value = System_ELFAssembly_ABI_Linux },
    [6] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.Solaris", .value = System_ELFAssembly_ABI_Solaris },
    [7] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.AIX", .value = System_ELFAssembly_ABI_AIX },
    [8] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.IRIX", .value = System_ELFAssembly_ABI_IRIX },
    [9] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.FreeBSD", .value = System_ELFAssembly_ABI_FreeBSD },
    [10] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.TRU64", .value = System_ELFAssembly_ABI_TRU64 },
    [11] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.Modesto", .value = System_ELFAssembly_ABI_Modesto },
    [12] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.OpenBSD", .value = System_ELFAssembly_ABI_OpenBSD },
    [13] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.ARM_EABI", .value = System_ELFAssembly_ABI_ARM_EABI },
    [14] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.ARM", .value = System_ELFAssembly_ABI_ARM },
    [15] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ABI.Standalone", .value = System_ELFAssembly_ABI_Standalone },
};

struct System_Type  System_ELFAssembly_ABIType = { .base = { .type = typeof(System_Type) },
    .name = "ELFAssembly.ABI",
    .size = sizeof(System_ELFAssembly_ABI),
	.fields = { .base = stack_System_Object(System_Type_FieldInfoArray),
        .value = &System_ELFAssembly_ABITypeFields, .length = sizeof_array(System_ELFAssembly_ABITypeFields),
    },
};

struct System_Type_FieldInfo  System_ELFAssembly_AssemblyTypeTypeFields[] = {
    [0] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.None", .value = System_ELFAssembly_AssemblyType_None },
    [1] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.Relocatable", .value = System_ELFAssembly_AssemblyType_Relocatable },
    [2] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.Executable", .value = System_ELFAssembly_AssemblyType_Executable },
    [3] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.Shared", .value = System_ELFAssembly_AssemblyType_Shared },
    [4] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.Core", .value = System_ELFAssembly_AssemblyType_Core },
    [5] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.OSSpecificLow", .value = System_ELFAssembly_AssemblyType_OSSpecificLow },
    [6] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.OSSpecificHigh", .value = System_ELFAssembly_AssemblyType_OSSpecificHigh },
    [7] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.ProcessorSpecificLow", .value = System_ELFAssembly_AssemblyType_ProcessorSpecificLow },
    [8] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AssemblyType.ProcessorSpecificHigh", .value = System_ELFAssembly_AssemblyType_ProcessorSpecificHigh },
};

struct System_Type  System_ELFAssembly_AssemblyTypeType = { .base = { .type = typeof(System_Type) },
    .name = "ELFAssembly.AssemblyType",
    .size = sizeof(System_ELFAssembly_AssemblyType),
	.fields = { .base = stack_System_Object(System_Type_FieldInfoArray),
        .value = &System_ELFAssembly_AssemblyTypeTypeFields, .length = sizeof_array(System_ELFAssembly_AssemblyTypeTypeFields),
    },
};

struct System_Type_FieldInfo  System_ELFAssembly_MachineTypeFields[] = {
    [0] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.None", .value = System_ELFAssembly_Machine_None },
    [1] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.M32", .value = System_ELFAssembly_Machine_M32 },
    [2] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SPARC", .value = System_ELFAssembly_Machine_SPARC },
    [3] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.386", .value = System_ELFAssembly_Machine_386 },
    [4] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.68K", .value = System_ELFAssembly_Machine_68K },
    [5] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.88K", .value = System_ELFAssembly_Machine_88K },
    [6] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.IAMCU", .value = System_ELFAssembly_Machine_IAMCU },
    [7] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.860", .value = System_ELFAssembly_Machine_860 },
    [8] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MIPS", .value = System_ELFAssembly_Machine_MIPS },
    [9] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.S370", .value = System_ELFAssembly_Machine_S370 },
    [10] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MIPS_RS3_LE", .value = System_ELFAssembly_Machine_MIPS_RS3_LE },
    [11] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PARISC", .value = System_ELFAssembly_Machine_PARISC },
    [12] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.VPP500", .value = System_ELFAssembly_Machine_VPP500 },
    [13] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SPARC32PLUS", .value = System_ELFAssembly_Machine_SPARC32PLUS },
    [14] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.960", .value = System_ELFAssembly_Machine_960 },
    [15] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PPC", .value = System_ELFAssembly_Machine_PPC },
    [16] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PPC64", .value = System_ELFAssembly_Machine_PPC64 },
    [17] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.S390", .value = System_ELFAssembly_Machine_S390 },
    [18] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SPU", .value = System_ELFAssembly_Machine_SPU },
    [19] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.V800", .value = System_ELFAssembly_Machine_V800 },
    [20] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.FR20", .value = System_ELFAssembly_Machine_FR20 },
    [21] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.RH32", .value = System_ELFAssembly_Machine_RH32 },
    [22] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.RCE", .value = System_ELFAssembly_Machine_RCE },
    [23] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ARM", .value = System_ELFAssembly_Machine_ARM },
    [24] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.FAKE_ALPHA", .value = System_ELFAssembly_Machine_FAKE_ALPHA },
    [25] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SH", .value = System_ELFAssembly_Machine_SH },
    [26] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SPARCV9", .value = System_ELFAssembly_Machine_SPARCV9 },
    [27] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TRICORE", .value = System_ELFAssembly_Machine_TRICORE },
    [28] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ARC", .value = System_ELFAssembly_Machine_ARC },
    [29] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.H8_300", .value = System_ELFAssembly_Machine_H8_300 },
    [30] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.H8_300H", .value = System_ELFAssembly_Machine_H8_300H },
    [31] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.H8S", .value = System_ELFAssembly_Machine_H8S },
    [32] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.H8_500", .value = System_ELFAssembly_Machine_H8_500 },
    [33] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.IA_64", .value = System_ELFAssembly_Machine_IA_64 },
    [34] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MIPS_X", .value = System_ELFAssembly_Machine_MIPS_X },
    [35] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.COLDFIRE", .value = System_ELFAssembly_Machine_COLDFIRE },
    [36] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.68HC12", .value = System_ELFAssembly_Machine_68HC12 },
    [37] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MMA", .value = System_ELFAssembly_Machine_MMA },
    [38] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PCP", .value = System_ELFAssembly_Machine_PCP },
    [39] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.NCPU", .value = System_ELFAssembly_Machine_NCPU },
    [40] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.NDR1", .value = System_ELFAssembly_Machine_NDR1 },
    [41] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.STARCORE", .value = System_ELFAssembly_Machine_STARCORE },
    [42] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ME16", .value = System_ELFAssembly_Machine_ME16 },
    [43] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ST100", .value = System_ELFAssembly_Machine_ST100 },
    [44] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TINYJ", .value = System_ELFAssembly_Machine_TINYJ },
    [45] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.X86_64", .value = System_ELFAssembly_Machine_X86_64 },
    [46] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PDSP", .value = System_ELFAssembly_Machine_PDSP },
    [47] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PDP10", .value = System_ELFAssembly_Machine_PDP10 },
    [48] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PDP11", .value = System_ELFAssembly_Machine_PDP11 },
    [49] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.FX66", .value = System_ELFAssembly_Machine_FX66 },
    [50] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ST9PLUS", .value = System_ELFAssembly_Machine_ST9PLUS },
    [51] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ST7", .value = System_ELFAssembly_Machine_ST7 },
    [52] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.68HC16", .value = System_ELFAssembly_Machine_68HC16 },
    [53] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.68HC11", .value = System_ELFAssembly_Machine_68HC11 },
    [54] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.68HC08", .value = System_ELFAssembly_Machine_68HC08 },
    [55] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.68HC05", .value = System_ELFAssembly_Machine_68HC05 },
    [56] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SVX", .value = System_ELFAssembly_Machine_SVX },
    [57] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ST19", .value = System_ELFAssembly_Machine_ST19 },
    [58] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.VAX", .value = System_ELFAssembly_Machine_VAX },
    [59] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CRIS", .value = System_ELFAssembly_Machine_CRIS },
    [60] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.JAVELIN", .value = System_ELFAssembly_Machine_JAVELIN },
    [61] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.FIREPATH", .value = System_ELFAssembly_Machine_FIREPATH },
    [62] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ZSP", .value = System_ELFAssembly_Machine_ZSP },
    [63] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MMIX", .value = System_ELFAssembly_Machine_MMIX },
    [64] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.HUANY", .value = System_ELFAssembly_Machine_HUANY },
    [65] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PRISM", .value = System_ELFAssembly_Machine_PRISM },
    [66] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.AVR", .value = System_ELFAssembly_Machine_AVR },
    [67] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.FR30", .value = System_ELFAssembly_Machine_FR30 },
    [68] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.D10V", .value = System_ELFAssembly_Machine_D10V },
    [69] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.D30V", .value = System_ELFAssembly_Machine_D30V },
    [70] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.V850", .value = System_ELFAssembly_Machine_V850 },
    [71] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.M32R", .value = System_ELFAssembly_Machine_M32R },
    [72] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MN10300", .value = System_ELFAssembly_Machine_MN10300 },
    [73] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MN10200", .value = System_ELFAssembly_Machine_MN10200 },
    [74] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.PJ", .value = System_ELFAssembly_Machine_PJ },
    [75] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.OPENRISC", .value = System_ELFAssembly_Machine_OPENRISC },
    [76] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ARC_COMPACT", .value = System_ELFAssembly_Machine_ARC_COMPACT },
    [77] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.XTENSA", .value = System_ELFAssembly_Machine_XTENSA },
    [78] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.VIDEOCORE", .value = System_ELFAssembly_Machine_VIDEOCORE },
    [79] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TMM_GPP", .value = System_ELFAssembly_Machine_TMM_GPP },
    [80] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.NS32K", .value = System_ELFAssembly_Machine_NS32K },
    [81] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TPC", .value = System_ELFAssembly_Machine_TPC },
    [82] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SNP1K", .value = System_ELFAssembly_Machine_SNP1K },
    [83] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ST200", .value = System_ELFAssembly_Machine_ST200 },
    [84] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.IP2K", .value = System_ELFAssembly_Machine_IP2K },
    [85] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MAX", .value = System_ELFAssembly_Machine_MAX },
    [86] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CR", .value = System_ELFAssembly_Machine_CR },
    [87] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.F2MC16", .value = System_ELFAssembly_Machine_F2MC16 },
    [88] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MSP430", .value = System_ELFAssembly_Machine_MSP430 },
    [89] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.BLACKFIN", .value = System_ELFAssembly_Machine_BLACKFIN },
    [90] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SE_C33", .value = System_ELFAssembly_Machine_SE_C33 },
    [91] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SEP", .value = System_ELFAssembly_Machine_SEP },
    [92] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ARCA", .value = System_ELFAssembly_Machine_ARCA },
    [93] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.UNICORE", .value = System_ELFAssembly_Machine_UNICORE },
    [94] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.EXCESS", .value = System_ELFAssembly_Machine_EXCESS },
    [95] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.DXP", .value = System_ELFAssembly_Machine_DXP },
    [96] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ALTERA_NIOS2", .value = System_ELFAssembly_Machine_ALTERA_NIOS2 },
    [97] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CRX", .value = System_ELFAssembly_Machine_CRX },
    [98] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.XGATE", .value = System_ELFAssembly_Machine_XGATE },
    [99] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.C166", .value = System_ELFAssembly_Machine_C166 },
    [100] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.M16C", .value = System_ELFAssembly_Machine_M16C },
    [101] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.DSPIC30F", .value = System_ELFAssembly_Machine_DSPIC30F },
    [102] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CE", .value = System_ELFAssembly_Machine_CE },
    [103] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.M32C", .value = System_ELFAssembly_Machine_M32C },
    [104] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TSK3000", .value = System_ELFAssembly_Machine_TSK3000 },
    [105] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.RS08", .value = System_ELFAssembly_Machine_RS08 },
    [106] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SHARC", .value = System_ELFAssembly_Machine_SHARC },
    [107] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ECOG2", .value = System_ELFAssembly_Machine_ECOG2 },
    [108] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SCORE7", .value = System_ELFAssembly_Machine_SCORE7 },
    [109] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.DSP24", .value = System_ELFAssembly_Machine_DSP24 },
    [110] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.VIDEOCORE3", .value = System_ELFAssembly_Machine_VIDEOCORE3 },
    [111] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.LATTICEMICO32", .value = System_ELFAssembly_Machine_LATTICEMICO32 },
    [112] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SE_C17", .value = System_ELFAssembly_Machine_SE_C17 },
    [113] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TI_C6000", .value = System_ELFAssembly_Machine_TI_C6000 },
    [114] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TI_C2000", .value = System_ELFAssembly_Machine_TI_C2000 },
    [115] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TI_C5500", .value = System_ELFAssembly_Machine_TI_C5500 },
    [116] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TI_ARP32", .value = System_ELFAssembly_Machine_TI_ARP32 },
    [117] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TI_PRU", .value = System_ELFAssembly_Machine_TI_PRU },
    [118] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MMDSP_PLUS", .value = System_ELFAssembly_Machine_MMDSP_PLUS },
    [119] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CYPRESS_M8C", .value = System_ELFAssembly_Machine_CYPRESS_M8C },
    [120] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.R32C", .value = System_ELFAssembly_Machine_R32C },
    [121] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TRIMEDIA", .value = System_ELFAssembly_Machine_TRIMEDIA },
    [122] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.QDSP6", .value = System_ELFAssembly_Machine_QDSP6 },
    [123] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.8051", .value = System_ELFAssembly_Machine_8051 },
    [124] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.STXP7X", .value = System_ELFAssembly_Machine_STXP7X },
    [125] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.NDS32", .value = System_ELFAssembly_Machine_NDS32 },
    [126] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ECOG1X", .value = System_ELFAssembly_Machine_ECOG1X },
    [127] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MAXQ30", .value = System_ELFAssembly_Machine_MAXQ30 },
    [128] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.XIMO16", .value = System_ELFAssembly_Machine_XIMO16 },
    [129] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MANIK", .value = System_ELFAssembly_Machine_MANIK },
    [130] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CRAYNV2", .value = System_ELFAssembly_Machine_CRAYNV2 },
    [131] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.RX", .value = System_ELFAssembly_Machine_RX },
    [132] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.METAG", .value = System_ELFAssembly_Machine_METAG },
    [133] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MCST_ELBRUS", .value = System_ELFAssembly_Machine_MCST_ELBRUS },
    [134] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ECOG16", .value = System_ELFAssembly_Machine_ECOG16 },
    [135] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CR16", .value = System_ELFAssembly_Machine_CR16 },
    [136] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ETPU", .value = System_ELFAssembly_Machine_ETPU },
    [137] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.SLE9X", .value = System_ELFAssembly_Machine_SLE9X },
    [138] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.L10M", .value = System_ELFAssembly_Machine_L10M },
    [139] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.K10M", .value = System_ELFAssembly_Machine_K10M },
    [140] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.AARCH64", .value = System_ELFAssembly_Machine_AARCH64 },
    [141] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.AVR32", .value = System_ELFAssembly_Machine_AVR32 },
    [142] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.STM8", .value = System_ELFAssembly_Machine_STM8 },
    [143] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TILE64", .value = System_ELFAssembly_Machine_TILE64 },
    [144] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TILEPRO", .value = System_ELFAssembly_Machine_TILEPRO },
    [145] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MICROBLAZE", .value = System_ELFAssembly_Machine_MICROBLAZE },
    [146] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CUDA", .value = System_ELFAssembly_Machine_CUDA },
    [147] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.TILEGX", .value = System_ELFAssembly_Machine_TILEGX },
    [148] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CLOUDSHIELD", .value = System_ELFAssembly_Machine_CLOUDSHIELD },
    [149] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.COREA_1ST", .value = System_ELFAssembly_Machine_COREA_1ST },
    [150] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.COREA_2ND", .value = System_ELFAssembly_Machine_COREA_2ND },
    [151] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ARC_COMPACT2", .value = System_ELFAssembly_Machine_ARC_COMPACT2 },
    [152] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.OPEN8", .value = System_ELFAssembly_Machine_OPEN8 },
    [153] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.RL78", .value = System_ELFAssembly_Machine_RL78 },
    [154] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.VIDEOCORE5", .value = System_ELFAssembly_Machine_VIDEOCORE5 },
    [155] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.78KOR", .value = System_ELFAssembly_Machine_78KOR },
    [156] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.56800EX", .value = System_ELFAssembly_Machine_56800EX },
    [157] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.BA1", .value = System_ELFAssembly_Machine_BA1 },
    [158] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.BA2", .value = System_ELFAssembly_Machine_BA2 },
    [159] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.XCORE", .value = System_ELFAssembly_Machine_XCORE },
    [160] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MCHP_PIC", .value = System_ELFAssembly_Machine_MCHP_PIC },
    [161] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.KM32", .value = System_ELFAssembly_Machine_KM32 },
    [162] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.KMX32", .value = System_ELFAssembly_Machine_KMX32 },
    [163] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.EMX16", .value = System_ELFAssembly_Machine_EMX16 },
    [164] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.EMX8", .value = System_ELFAssembly_Machine_EMX8 },
    [165] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.KVARC", .value = System_ELFAssembly_Machine_KVARC },
    [166] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CDP", .value = System_ELFAssembly_Machine_CDP },
    [167] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.COGE", .value = System_ELFAssembly_Machine_COGE },
    [168] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.COOL", .value = System_ELFAssembly_Machine_COOL },
    [169] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.NORC", .value = System_ELFAssembly_Machine_NORC },
    [170] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CSR_KALIMBA", .value = System_ELFAssembly_Machine_CSR_KALIMBA },
    [171] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.Z80", .value = System_ELFAssembly_Machine_Z80 },
    [172] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.VISIUM", .value = System_ELFAssembly_Machine_VISIUM },
    [173] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.FT32", .value = System_ELFAssembly_Machine_FT32 },
    [174] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.MOXIE", .value = System_ELFAssembly_Machine_MOXIE },
    [175] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.AMDGPU", .value = System_ELFAssembly_Machine_AMDGPU },
    [176] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.RISCV", .value = System_ELFAssembly_Machine_RISCV },
    [177] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.BPF", .value = System_ELFAssembly_Machine_BPF },
    [178] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.CSKY", .value = System_ELFAssembly_Machine_CSKY },
    [179] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.Machine.ALPHA", .value = System_ELFAssembly_Machine_ALPHA },
};

struct System_Type  System_ELFAssembly_MachineType = { .base = { .type = typeof(System_Type) },
    .name = "ELFAssembly.Machine",
    .size = sizeof(System_ELFAssembly_Machine),
	.fields = { .base = stack_System_Object(System_Type_FieldInfoArray),
        .value = &System_ELFAssembly_MachineTypeFields, .length = sizeof_array(System_ELFAssembly_MachineTypeFields),
    },
};

struct System_Type_FieldInfo  System_ELFAssembly_ProgramTypeTypeFields[] = {
    [0] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.Null", .value = System_ELFAssembly_ProgramType_Null },
    [1] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.Loadable", .value = System_ELFAssembly_ProgramType_Loadable },
    [2] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.Dynamic", .value = System_ELFAssembly_ProgramType_Dynamic },
    [3] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.Interpreter", .value = System_ELFAssembly_ProgramType_Interpreter },
    [4] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.AuxiliaryNote", .value = System_ELFAssembly_ProgramType_AuxiliaryNote },
    [5] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.SHLIB", .value = System_ELFAssembly_ProgramType_SHLIB },
    [6] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.ProgramHeader", .value = System_ELFAssembly_ProgramType_ProgramHeader },
    [7] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.ThreadLocalStorage", .value = System_ELFAssembly_ProgramType_ThreadLocalStorage },
    [8] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.NUMBER", .value = System_ELFAssembly_ProgramType_NUMBER },
    [9] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.GNU_EHFRAME", .value = System_ELFAssembly_ProgramType_GNU_EHFRAME },
    [10] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.GNU_Stack", .value = System_ELFAssembly_ProgramType_GNU_Stack },
    [11] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramType.GNU_ReadOnlyRelocation", .value = System_ELFAssembly_ProgramType_GNU_ReadOnlyRelocation },
};

struct System_Type  System_ELFAssembly_ProgramTypeType = { .base = { .type = typeof(System_Type) },
    .name = "ELFAssembly.ProgramType",
    .size = sizeof(System_ELFAssembly_ProgramType),
	.fields = { .base = stack_System_Object(System_Type_FieldInfoArray),
        .value = &System_ELFAssembly_ProgramTypeTypeFields, .length = sizeof_array(System_ELFAssembly_ProgramTypeTypeFields),
    },
};

struct System_Type_FieldInfo  System_ELFAssembly_ProgramFlagsTypeFields[] = {
    [0] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramFlags.None", .value = System_ELFAssembly_ProgramFlags_None },
    [1] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramFlags.Executable", .value = System_ELFAssembly_ProgramFlags_Executable },
    [2] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramFlags.Writable", .value = System_ELFAssembly_ProgramFlags_Writable },
    [3] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramFlags.Readable", .value = System_ELFAssembly_ProgramFlags_Readable },
    [4] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramFlags.OSSpecific", .value = System_ELFAssembly_ProgramFlags_OSSpecific },
    [5] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.ProgramFlags.ProcessorSpecific", .value = System_ELFAssembly_ProgramFlags_ProcessorSpecific },
};

struct System_Type  System_ELFAssembly_ProgramFlagsType = { .base = { .type = typeof(System_Type) },
    .name = "ELFAssembly.ProgramFlags",
    .size = sizeof(System_ELFAssembly_ProgramFlags),
	.fields = { .base = stack_System_Object(System_Type_FieldInfoArray),
        .value = &System_ELFAssembly_ProgramFlagsTypeFields, .length = sizeof_array(System_ELFAssembly_ProgramFlagsTypeFields),
    },
};

struct System_Type_FieldInfo  System_ELFAssembly_DynamicTypeTypeFields[] = {
    [0] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.NULL", .value = System_ELFAssembly_DynamicType_NULL },
    [1] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.NEEDED", .value = System_ELFAssembly_DynamicType_NEEDED },
    [2] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.PLTRELSZ", .value = System_ELFAssembly_DynamicType_PLTRELSZ },
    [3] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.PLTGOT", .value = System_ELFAssembly_DynamicType_PLTGOT },
    [4] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.HASH", .value = System_ELFAssembly_DynamicType_HASH },
    [5] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.STRTAB", .value = System_ELFAssembly_DynamicType_STRTAB },
    [6] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.SYMTAB", .value = System_ELFAssembly_DynamicType_SYMTAB },
    [7] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RELA", .value = System_ELFAssembly_DynamicType_RELA },
    [8] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RELASZ", .value = System_ELFAssembly_DynamicType_RELASZ },
    [9] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RELAENT", .value = System_ELFAssembly_DynamicType_RELAENT },
    [10] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.STRSZ", .value = System_ELFAssembly_DynamicType_STRSZ },
    [11] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.SYMENT", .value = System_ELFAssembly_DynamicType_SYMENT },
    [12] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.INIT", .value = System_ELFAssembly_DynamicType_INIT },
    [13] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.FINI", .value = System_ELFAssembly_DynamicType_FINI },
    [14] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.SONAME", .value = System_ELFAssembly_DynamicType_SONAME },
    [15] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RPATH", .value = System_ELFAssembly_DynamicType_RPATH },
    [16] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.SYMBOLIC", .value = System_ELFAssembly_DynamicType_SYMBOLIC },
    [17] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.REL", .value = System_ELFAssembly_DynamicType_REL },
    [18] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RELSZ", .value = System_ELFAssembly_DynamicType_RELSZ },
    [19] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RELENT", .value = System_ELFAssembly_DynamicType_RELENT },
    [20] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.PLTREL", .value = System_ELFAssembly_DynamicType_PLTREL },
    [21] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.DEBUG", .value = System_ELFAssembly_DynamicType_DEBUG },
    [22] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.TEXTREL", .value = System_ELFAssembly_DynamicType_TEXTREL },
    [23] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.JMPREL", .value = System_ELFAssembly_DynamicType_JMPREL },
    [24] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.BIND_NOW", .value = System_ELFAssembly_DynamicType_BIND_NOW },
    [25] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.INIT_ARRAY", .value = System_ELFAssembly_DynamicType_INIT_ARRAY },
    [26] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.FINI_ARRAY", .value = System_ELFAssembly_DynamicType_FINI_ARRAY },
    [27] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.INIT_ARRAYSZ", .value = System_ELFAssembly_DynamicType_INIT_ARRAYSZ },
    [28] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.FINI_ARRAYSZ", .value = System_ELFAssembly_DynamicType_FINI_ARRAYSZ },
    [29] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RUNPATH", .value = System_ELFAssembly_DynamicType_RUNPATH },
    [30] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.FLAGS", .value = System_ELFAssembly_DynamicType_FLAGS },
    [31] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.ENCODING", .value = System_ELFAssembly_DynamicType_ENCODING },
    [32] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.PREINIT_ARRAY", .value = System_ELFAssembly_DynamicType_PREINIT_ARRAY },
    [33] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.PREINIT_ARRAYSZ", .value = System_ELFAssembly_DynamicType_PREINIT_ARRAYSZ },
    [34] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.SYMTAB_SHNDX", .value = System_ELFAssembly_DynamicType_SYMTAB_SHNDX },
    [35] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.NUM", .value = System_ELFAssembly_DynamicType_NUM },
    [36] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.LOOS", .value = System_ELFAssembly_DynamicType_LOOS },
    [37] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.HIOS", .value = System_ELFAssembly_DynamicType_HIOS },
    [38] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.LOPROC", .value = System_ELFAssembly_DynamicType_LOPROC },
    [39] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.HIPROC", .value = System_ELFAssembly_DynamicType_HIPROC },
    [40] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.MIPSNUM", .value = System_ELFAssembly_DynamicType_MIPSNUM },
    [41] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.PROCNUM", .value = System_ELFAssembly_DynamicType_PROCNUM },
    [42] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VALRNGLO", .value = System_ELFAssembly_DynamicType_VALRNGLO },
    [43] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.GNU_PRELINKED", .value = System_ELFAssembly_DynamicType_GNU_PRELINKED },
    [44] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.GNU_CONFLICTSZ", .value = System_ELFAssembly_DynamicType_GNU_CONFLICTSZ },
    [45] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.GNU_LIBLISTSZ", .value = System_ELFAssembly_DynamicType_GNU_LIBLISTSZ },
    [46] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.CHECKSUM", .value = System_ELFAssembly_DynamicType_CHECKSUM },
    [47] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.PLTPADSZ", .value = System_ELFAssembly_DynamicType_PLTPADSZ },
    [48] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.MOVEENT", .value = System_ELFAssembly_DynamicType_MOVEENT },
    [49] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.MOVESZ", .value = System_ELFAssembly_DynamicType_MOVESZ },
    [50] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.FEATURE_1", .value = System_ELFAssembly_DynamicType_FEATURE_1 },
    [51] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.POSFLAG_1", .value = System_ELFAssembly_DynamicType_POSFLAG_1 },
    [52] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.SYMINSZ", .value = System_ELFAssembly_DynamicType_SYMINSZ },
    [53] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.SYMINENT", .value = System_ELFAssembly_DynamicType_SYMINENT },
    [54] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VALRNGHI", .value = System_ELFAssembly_DynamicType_VALRNGHI },
    [55] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VALNUM", .value = System_ELFAssembly_DynamicType_VALNUM },
    [56] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.ADDRRNGLO", .value = System_ELFAssembly_DynamicType_ADDRRNGLO },
    [57] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.GNU_HASH", .value = System_ELFAssembly_DynamicType_GNU_HASH },
    [58] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.TLSDESC_PLT", .value = System_ELFAssembly_DynamicType_TLSDESC_PLT },
    [59] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.TLSDESC_GOT", .value = System_ELFAssembly_DynamicType_TLSDESC_GOT },
    [60] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.GNU_CONFLICT", .value = System_ELFAssembly_DynamicType_GNU_CONFLICT },
    [61] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.GNU_LIBLIST", .value = System_ELFAssembly_DynamicType_GNU_LIBLIST },
    [62] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.CONFIG", .value = System_ELFAssembly_DynamicType_CONFIG },
    [63] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.DEPAUDIT", .value = System_ELFAssembly_DynamicType_DEPAUDIT },
    [64] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.AUDIT", .value = System_ELFAssembly_DynamicType_AUDIT },
    [65] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.PLTPAD", .value = System_ELFAssembly_DynamicType_PLTPAD },
    [66] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.MOVETAB", .value = System_ELFAssembly_DynamicType_MOVETAB },
    [67] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.SYMINFO", .value = System_ELFAssembly_DynamicType_SYMINFO },
    [68] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.ADDRRNGHI", .value = System_ELFAssembly_DynamicType_ADDRRNGHI },
    [69] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.ADDRNUM", .value = System_ELFAssembly_DynamicType_ADDRNUM },
    [70] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VERSYM", .value = System_ELFAssembly_DynamicType_VERSYM },
    [71] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RELACOUNT", .value = System_ELFAssembly_DynamicType_RELACOUNT },
    [72] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.RELCOUNT", .value = System_ELFAssembly_DynamicType_RELCOUNT },
    [73] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.FLAGS_1", .value = System_ELFAssembly_DynamicType_FLAGS_1 },
    [74] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VERDEF", .value = System_ELFAssembly_DynamicType_VERDEF },
    [75] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VERDEFNUM", .value = System_ELFAssembly_DynamicType_VERDEFNUM },
    [76] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VERNEED", .value = System_ELFAssembly_DynamicType_VERNEED },
    [77] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VERNEEDNUM", .value = System_ELFAssembly_DynamicType_VERNEEDNUM },
    [78] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.VERSIONTAGNUM", .value = System_ELFAssembly_DynamicType_VERSIONTAGNUM },
    [79] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.AUXILIARY", .value = System_ELFAssembly_DynamicType_AUXILIARY },
    [80] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.FILTER", .value = System_ELFAssembly_DynamicType_FILTER },
    [81] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.DynamicType.EXTRANUM", .value = System_ELFAssembly_DynamicType_EXTRANUM },
};

struct System_Type  System_ELFAssembly_DynamicTypeType = { .base = { .type = typeof(System_Type) },
    .name = "ELFAssembly.DynamicType",
    .size = sizeof(System_ELFAssembly_DynamicType),
	.fields = { .base = stack_System_Object(System_Type_FieldInfoArray),
        .value = &System_ELFAssembly_DynamicTypeTypeFields, .length = sizeof_array(System_ELFAssembly_DynamicTypeTypeFields),
    },
};

struct System_Type_FieldInfo  System_ELFAssembly_AuxTypeTypeFields[] = {
    [0] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.NULL", .value = System_ELFAssembly_AuxType_NULL },
    [1] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.IGNORE", .value = System_ELFAssembly_AuxType_IGNORE },
    [2] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.EXECFD", .value = System_ELFAssembly_AuxType_EXECFD },
    [3] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.PHDR", .value = System_ELFAssembly_AuxType_PHDR },
    [4] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.PHENT", .value = System_ELFAssembly_AuxType_PHENT },
    [5] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.PHNUM", .value = System_ELFAssembly_AuxType_PHNUM },
    [6] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.PAGESZ", .value = System_ELFAssembly_AuxType_PAGESZ },
    [7] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.BASE", .value = System_ELFAssembly_AuxType_BASE },
    [8] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.FLAGS", .value = System_ELFAssembly_AuxType_FLAGS },
    [9] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.ENTRY", .value = System_ELFAssembly_AuxType_ENTRY },
    [10] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.NOTELF", .value = System_ELFAssembly_AuxType_NOTELF },
    [11] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.UID", .value = System_ELFAssembly_AuxType_UID },
    [12] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.EUID", .value = System_ELFAssembly_AuxType_EUID },
    [13] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.GID", .value = System_ELFAssembly_AuxType_GID },
    [14] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.EGID", .value = System_ELFAssembly_AuxType_EGID },
    [15] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.CLKTCK", .value = System_ELFAssembly_AuxType_CLKTCK },
    [16] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.PLATFORM", .value = System_ELFAssembly_AuxType_PLATFORM },
    [17] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.HWCAP", .value = System_ELFAssembly_AuxType_HWCAP },
    [18] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.FPUCW", .value = System_ELFAssembly_AuxType_FPUCW },
    [19] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.DCACHEBSIZE", .value = System_ELFAssembly_AuxType_DCACHEBSIZE },
    [20] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.ICACHEBSIZE", .value = System_ELFAssembly_AuxType_ICACHEBSIZE },
    [21] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.UCACHEBSIZE", .value = System_ELFAssembly_AuxType_UCACHEBSIZE },
    [22] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.IGNOREPPC", .value = System_ELFAssembly_AuxType_IGNOREPPC },
    [23] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.SECURE", .value = System_ELFAssembly_AuxType_SECURE },
    [24] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.BASE_PLATFORM", .value = System_ELFAssembly_AuxType_BASE_PLATFORM },
    [25] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.RANDOM", .value = System_ELFAssembly_AuxType_RANDOM },
    [26] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.HWCAP2", .value = System_ELFAssembly_AuxType_HWCAP2 },
    [27] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.EXECFN", .value = System_ELFAssembly_AuxType_EXECFN },
    [28] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.SYSINFO", .value = System_ELFAssembly_AuxType_SYSINFO },
    [29] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.SYSINFO_EHDR", .value = System_ELFAssembly_AuxType_SYSINFO_EHDR },
    [30] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L1I_CACHESHAPE", .value = System_ELFAssembly_AuxType_L1I_CACHESHAPE },
    [31] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L1D_CACHESHAPE", .value = System_ELFAssembly_AuxType_L1D_CACHESHAPE },
    [32] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L2_CACHESHAPE", .value = System_ELFAssembly_AuxType_L2_CACHESHAPE },
    [33] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L3_CACHESHAPE", .value = System_ELFAssembly_AuxType_L3_CACHESHAPE },
    [34] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L1I_CACHESIZE", .value = System_ELFAssembly_AuxType_L1I_CACHESIZE },
    [35] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L1I_CACHEGEOMETRY", .value = System_ELFAssembly_AuxType_L1I_CACHEGEOMETRY },
    [36] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L1D_CACHESIZE", .value = System_ELFAssembly_AuxType_L1D_CACHESIZE },
    [37] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L1D_CACHEGEOMETRY", .value = System_ELFAssembly_AuxType_L1D_CACHEGEOMETRY },
    [38] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L2_CACHESIZE", .value = System_ELFAssembly_AuxType_L2_CACHESIZE },
    [39] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L2_CACHEGEOMETRY", .value = System_ELFAssembly_AuxType_L2_CACHEGEOMETRY },
    [40] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L3_CACHESIZE", .value = System_ELFAssembly_AuxType_L3_CACHESIZE },
    [41] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.L3_CACHEGEOMETRY", .value = System_ELFAssembly_AuxType_L3_CACHEGEOMETRY },
    [42] = { .base = stack_System_Object(System_Type_FieldInfo), .name = "ELFAssembly.AuxType.MINSIGSTKSZ", .value = System_ELFAssembly_AuxType_MINSIGSTKSZ },
};

struct System_Type  System_ELFAssembly_AuxTypeType = { .base = { .type = typeof(System_Type) },
    .name = "ELFAssembly.AuxType",
    .size = sizeof(System_ELFAssembly_AuxType),
	.fields = { .base = stack_System_Object(System_Type_FieldInfoArray),
        .value = &System_ELFAssembly_AuxTypeTypeFields, .length = sizeof_array(System_ELFAssembly_AuxTypeTypeFields),
    },
};

#endif